name: fitrepository
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pytorch>=1.9.0
  - torchvision
  - cudatoolkit=11.3
  - flask>=2.0.0
  - numpy>=1.19.0
  - trimesh>=3.9.0
  - python-dotenv>=0.19.0
  - pyopengl>=3.1.0
  - pip
  - pip:
    - "git+https://github.com/vchoutas/smplx.git"
